### ISSUE TITLE
store unaligned fault not save in inst->fault

### ISSUE THREAD

**Issue by zybzzz** [OpenXiangShan/GEM5#234]
## question
We can see that in ```lsq.cc pushRequest```, the program tries to handle the unaligned store when the inserted request is a store request.

https://github.com/OpenXiangShan/GEM5/blob/38a5253405119e5e63d3cb6e7fad90b691fa111d/src/cpu/o3/lsq.cc#L918C1-L924C6

Here the program returns the fault as soon as it detects an unaligned store memory access.

https://github.com/OpenXiangShan/GEM5/blob/38a5253405119e5e63d3cb6e7fad90b691fa111d/src/cpu/o3/lsq_unit.cc#L1021C1-L1037C6

After receiving this exception, ```lsq_unit.cc executeStore``` still returns the exception to the calling function.

https://github.com/OpenXiangShan/GEM5/blob/38a5253405119e5e63d3cb6e7fad90b691fa111d/src/cpu/o3/iew.cc#L1425C15-L1448C18

Unfortunately, in ```iew.cc```, **the fault is not saved to inst->fault and is sent to the commit stage, which will cause an error once the store is committed.**

## analyze

Maybe there is a point to the design itself, but I just don't understand the code and what it means, and then this issue of mine will be meaningless.（有可能是我没读懂代码，这部分的设计本身就是这样）

---
But if it wasn't, I would think that this error would have been detected early on, since **we have difftest turned on at all times, but the reality is that difftest has never reported a problem due to this error**, which is confusing to me.

So I picked at least 4 checkpoints to analyze their logs and summarized the following points:
1.  Store unaligned faults are inherently rare, and in most checkpoints no such faults are generated, so difftest reports no errors.
2.  In the only checkpoint that produced store unaligned faults, each of the unaligned faults was due to the pipeline squash of the previous command **causing the store not to be finalized for commit**, so difftest did not report the problem.

---

If this is indeed a bug, I think a better solution would be to move the unaligned store judgment to the, ```lsqunit.cc write``` method, as is the case with the unaligned load judgment, and be careful to save the fault to inst.

@shinezyy @jensen-yan

**Comment by tastynoob** [comment]
XS-GEM5 did not add store-misaligned fault, only has load-misaligned fault.

**Comment by happy-lx** [comment]
I encountered the same problem too when reading the code before.

![image](https://github.com/user-attachments/assets/00fa1c8b-05c2-4778-8ee4-b5d68756d096)
I observed that the function `initiateAcc` would set fault to the DynInst which later calls `pushRequest` in lsq.cc.

**Comment by tastynoob** [comment]
If store has page fault or others, it will set fault at PushRequest.
![image](https://github.com/user-attachments/assets/d86ab940-b944-45de-bb49-7c25c658ad60)

**Comment by zybzzz** [comment]
> I encountered the same problem too when reading the code before.
> 
> ![image](https://private-user-images.githubusercontent.com/54952983/395992030-00fa1c8b-05c2-4778-8ee4-b5d68756d096.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzM1MjQsIm5iZiI6MTczNDMzMzIyNCwicGF0aCI6Ii81NDk1Mjk4My8zOTU5OTIwMzAtMDBmYTFjOGItMDVjMi00Nzc4LThlZTQtYjVkNjg3NTZkMDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA3MTM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNTYzNWFhZTEyMjY0MWJiZmUwNjM4MThiOWFjOTFkNzQwNmU3NjZjMDk2Y2ZkYzQ4OGMzOGY4MDc0N2Q0ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u9rblI9wIhc8l15_HxXZNvMjG1e9Z3vKCRMxDu89gFs) I observed that the function `initiateAcc` would set fault to the DynInst which later calls `pushRequest` in lsq.cc.

You are correct, I didn't notice that when I was reading the code. Thanks. Actually the unaligned store is still saved by inst->fault.

**Comment by zybzzz** [comment]
> If store has page fault or others, it will set fault at PushRequest. ![image](https://private-user-images.githubusercontent.com/59657499/395992429-d86ab940-b944-45de-bb49-7c25c658ad60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzM1MjQsIm5iZiI6MTczNDMzMzIyNCwicGF0aCI6Ii81OTY1NzQ5OS8zOTU5OTI0MjktZDg2YWI5NDAtYjk0NC00NWRlLWJiNDktN2MyNWM2NThhZDYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA3MTM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMDI0MDJmYjQ1YmI2ZWQzYTk2OGVjNWJkOWY2ZTFmOGVkNTUxNTI0YzkxMzJhYjc5YTA3MmRmNjAwZGU4Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6ga2MqyYRcI7pUP9a_hxW1xs-ZNeTUEW_-pdrwW9OxE)

Thanks, I understand the code you pointed out on your side. But as @happy-lx said, unaligned stores are actually still saved and processed. xs-gem5 currently supports unalign store processing.

**Comment by tastynoob** [comment]
Yes, I just found out store and load's make fault were distributed in different locations

**Comment by zybzzz** [comment]
![image](https://github.com/user-attachments/assets/bb63dffc-5e65-4a06-a028-96d46bf7e438)

This part of the code seems fine for now, but moving it to ```write``` might be a better option. I haven't analyzed this situation yet. @tastynoob
