### ISSUE TITLE
Forget to clear the `_ever_prefetched` flag in the CacheBlk::invalidate() function

### ISSUE THREAD

**Issue by Kepontry** [OpenXiangShan/GEM5#44]
The function `clearPrefetched()` doesn't clear the `_ever_prefetched` flag. It seems that here we need a `clearEverPrefetched()` like function. When that is applied, there is a slight change in scores(<0.02).
https://github.com/OpenXiangShan/GEM5/blob/6a85ffb479c8c1ecff432ddd5801216b4e829580/src/mem/cache/cache_blk.hh#L205-L209

**Comment by shinezyy** [comment]
We will evaluate its impact on performance.

**Comment by tastynoob** [comment]
Fixed, use clearAllPrefetched()
