### ISSUE TITLE
自定义格式checkpoint

### ISSUE THREAD

**Issue by qqli579** [OpenXiangShan/GEM5#48]
为了在gem5 里支持你们自定义格式的checkpoint，gem5 做了哪些修改？有没有相应的提交？

**Comment by shinezyy** [comment]
主要修改：

3e58824d958f9a0bdb8ce4ad04eab32d0a18db47
bb5fe0ca763ec73b77329383d5a23492bb3b9685
96c583431028726562ef506c756e1bd539fbdca9
