### ISSUE TITLE
what is the performance of current backport branch

### ISSUE THREAD

**Issue by XiaPZ** [OpenXiangShan/GEM5#53]
I am trying to run some spec2006 benchmarks on xiangshan GEM5, currently I tried hmmer on backport branch, the weighted IPC is around 2.5 (spec2006 score is around 5.6 / GHz), that is far from 11 / GHz, so I am wondering what is the performance of current backport branch? Thanks

**Comment by shinezyy** [comment]
Can you give more details on how you "tried" hmmer and how you relate IPC of hmmer agaist spec2006 score?

**Comment by XiaPZ** [comment]
Sure, hmmer is built with gcc 11, O3 option, with rv64imafdc, score is calculated as ref_time / ((1 / IPC) * num_insts / 10^9 ).
For hmmer, there ref1 and ref2, so the score is ref_time / ((((1/IPC_ref1) * num_insts_ref1) + (1/IPC_ref2) * num_insts_ref2) / 10^9).

**Comment by XiaPZ** [comment]
checkpoint is collected with NEMU, and run with util/warmup_scripts/simple_gem5.sh

**Comment by shinezyy** [comment]
hmmer's performance is sensitive to B-extension, try gcc 12 with rv64gc_zba_zbb_zbc_zbs

**Comment by XiaPZ** [comment]
After recompiled hmmer with B-extension, now the IPC is around 4.9,  you are right, hmmer is sensitive to B-extension.

**Comment by XiaPZ** [comment]
Thanks for your help @shinezyy
